// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxle9HZnjpdMI5Ja0D2WKP7uuD22zZdO4',
    appId: '1:889305203968:web:f3aeb17d285c75225c5fe5',
    messagingSenderId: '889305203968',
    projectId: 'sifat-music',
    authDomain: 'sifat-music.firebaseapp.com',
    storageBucket: 'sifat-music.firebasestorage.app',
    measurementId: 'G-5BSQ787H9E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiLjpspry7HDwpPKkCMPnzpBro7pwcSQI',
    appId: '1:889305203968:android:47173125f1da109d5c5fe5',
    messagingSenderId: '889305203968',
    projectId: 'sifat-music',
    storageBucket: 'sifat-music.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB--mKyB70H2_LZkrfA3Ky-zClvcaR6Vp8',
    appId: '1:889305203968:ios:034b330e731fb4895c5fe5',
    messagingSenderId: '889305203968',
    projectId: 'sifat-music',
    storageBucket: 'sifat-music.firebasestorage.app',
    iosBundleId: 'com.sifat.dev.sifataudio.sifatAudio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB--mKyB70H2_LZkrfA3Ky-zClvcaR6Vp8',
    appId: '1:889305203968:ios:034b330e731fb4895c5fe5',
    messagingSenderId: '889305203968',
    projectId: 'sifat-music',
    storageBucket: 'sifat-music.firebasestorage.app',
    iosBundleId: 'com.sifat.dev.sifataudio.sifatAudio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxle9HZnjpdMI5Ja0D2WKP7uuD22zZdO4',
    appId: '1:889305203968:web:6b4cb22b53921e7c5c5fe5',
    messagingSenderId: '889305203968',
    projectId: 'sifat-music',
    authDomain: 'sifat-music.firebaseapp.com',
    storageBucket: 'sifat-music.firebasestorage.app',
    measurementId: 'G-9ZPJWLKTM9',
  );
}